name: Village at Alum Creek
markdown: kramdown
prose:
  siteurl: 'http://www.villageatalumcreek.org/'
  relativeLinks: 'http://www.villageatalumcreek.org/api/links.jsonp'
  media: 'uploads'
  ignore:
    - /_layouts
    - /api
    - /images
    - /javascripts
    - /stylesheets
    - _config.yml
    - CNAME
    - index.html
    - .gitignore
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "Marty"
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "no-menu"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    pages/classifieds:
      - name: "layout"
        field:
          element: "hidden"
          value: "classifieds"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    pages/events:
      - name: "layout"
        field:
          element: "hidden"
          value: "events"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    pages/homeowners-association:
      - name: "layout"
        field:
          element: "hidden"
          value: "homeowners-association"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    pages/administrators-guide:
      - name: "layout"
        field:
          element: "hidden"
          value: "administrators-guide"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""

